# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# A scrape configuration containing exactly one endpoint to scrape:
# Scrape Targets config 
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'consul'
    consul_sd_configs:
      - server: '192.168.1.4:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: .*node_exporter.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_dc]
        target_label: datacenter
      - source_labels: [__meta_consul_service_metadata_group]
        target_label: group_server      
      - source_labels: [__meta_consul_service_metadata_status]
        target_label: status
      - source_labels: [__meta_consul_service_metadata_sys]
        target_label: sys

